---
title: "Section 2.9"
author: "Dr Richard Wilkinson"
date: "8 February 2016"
output:
  pdf_document: default
  html_document: default
---


```{r}
library(lme4)
load('MAS473.RData')
attach(raildata)

```


```{r}
library(ggplot2)
qplot(Rail, travel, geom='boxplot')

fm1.ml<-lmer(travel~1+(1|Rail),raildata,REML=F)
fm1.reml<-lmer(travel~1+(1|Rail),raildata)

logLik(fm1.ml)
logLik(fm1.reml)

logLik(fm1.reml, REML=FALSE) 

```

not the same thing as gives log likelihood at REML parameter estimates

```{r}
fm1<-lmer(travel~1+(1|Rail),raildata)
summary(fm1)
```

```{r}
lm1<-lm(travel~Rail, contrasts=list(Rail=contr.sum),raildata)
summary(lm1)
coef(lm1)[-1]
sum(-coef(lm1)[-1])
```


```{r}
coef(lm1)
sum(-coef(lm1)[-1]) # alpha_6
ranef(fm1.reml)
x <- ranef(fm1.reml)
sum(x$Rail)
```

estimate of beta for both models
```{r}

mean(travel)
sqrt(4.021^2/18)
sqrt(1/18*(3*615.31 + 16.17))

```

sjPlot library

```{r}
library(sjPlot)
sjp.lmer(fm1,sort.coef=T)
#sjp.lmer(fm1, type='fe')
sjp.lmer(fm1, type='re.qq')

```
